✨ build buttons in components
mewiemers/meet-albert pull request #20
Opened 2021-03-18 11:14 UTC by mewiemers

Fixes #13

add the first two buttons in storybook

2021-03-18 18:53 UTC, m-wiemers approved these changes
We are building an app. And Melli shows how it works ⛑

2021-03-19 11:14 UTC, phlgr requested changes
Gj 🚀

2021-03-19 11:14 UTC, phlgr commented on components/button/Button.module.css
> +  height: 2rem;
Would not set a fixed `height` and `width`, the Button should get it's size by the content it is carrying.

2021-03-19 11:14 UTC, phlgr commented on components/quizbutton/Quizbutton.module.css
> +}
You could create a new class standard which combines the standard attributes and remove the standard attributes from the color classes

2021-03-19 11:14 UTC, phlgr commented on components/quizbutton/Quizbutton.tsx
> +    <button className={styles[color]} {...props}>
```suggestion
    <button className={`${styles.standard} ${styles[color]}`} {...props}>
```

2021-03-19 14:56 UTC, merged